import { devices } from '../../dist/index.js'

describe('cy.emulate', () => {
  it('matches the iPhone 16 descriptor exactly', () => {
    cy.emulate('iPhone 16')
    cy.visit('/')

    const expected = devices['iPhone 16']

    cy.window().should((win) => {
      expect(win.innerWidth).to.eq(expected.viewport.width)
      expect(win.innerHeight).to.eq(expected.viewport.height)
      expect(win.devicePixelRatio).to.eq(expected.deviceScaleFactor)
      expect(win.navigator.userAgent).to.eq(expected.userAgent)
      expect(win.navigator.maxTouchPoints).to.eq(expected.maxTouchPoints ?? 5)
      expect('ontouchstart' in win).to.eq(true)
      expect(win.matchMedia('(hover: none)').matches).to.eq(true)
      expect(win.matchMedia('(pointer: coarse)').matches).to.eq(true)
      // iPhone 16's portrait content viewport (393x659, see devices.ts) is taller
      // than wide, so this must report portrait-primary.
      expect(win.screen.orientation.type).to.eq('portrait-primary')
      expect(win.screen.orientation.angle).to.eq(0)
    })
  })

  it('applies viewport/UA/DPR/media-queries immediately when called after cy.visit(), on an already-loaded page', () => {
    // Every other test in this file calls emulate() BEFORE visit() — that's the
    // primary documented pattern. This confirms the secondary pattern (a test
    // that's already mid-navigation and only decides to emulate afterward) still
    // gets correct signals without needing a fresh cy.visit().
    cy.visit('http://localhost:4599')
    cy.emulate('Pixel 9')

    const expected = devices['Pixel 9']

    cy.window().should((win) => {
      expect(win.innerWidth).to.eq(expected.viewport.width)
      expect(win.innerHeight).to.eq(expected.viewport.height)
      expect(win.devicePixelRatio).to.eq(expected.deviceScaleFactor)
      expect(win.navigator.userAgent).to.eq(expected.userAgent)
      expect(win.navigator.maxTouchPoints).to.eq(expected.maxTouchPoints ?? 5)
      expect(win.matchMedia('(hover: none)').matches).to.eq(true)
      expect(win.matchMedia('(pointer: coarse)').matches).to.eq(true)
      // Known, documented gap (see README): 'ontouchstart' in window is decided
      // at document-creation time in Chromium, not live-updatable — it does NOT
      // flip until the page reloads, unlike every other signal above. Verified
      // empirically: still false here, but true after cy.reload() (next test).
      expect('ontouchstart' in win).to.eq(false)
    })
  })

  it('applies ontouchstart too, once the already-emulated page is reloaded', () => {
    cy.visit('http://localhost:4599')
    cy.emulate('Pixel 9')
    cy.reload() // CDP overrides persist across reload — see src/index.ts
    cy.window().should((win) => {
      expect('ontouchstart' in win).to.eq(true)
    })
  })

  it('matches the Galaxy S25 descriptor exactly', () => {
    cy.emulate('Galaxy S25')
    cy.visit('/')

    const expected = devices['Galaxy S25']

    cy.window().should((win) => {
      expect(win.innerWidth).to.eq(expected.viewport.width)
      expect(win.innerHeight).to.eq(expected.viewport.height)
      expect(win.devicePixelRatio).to.eq(expected.deviceScaleFactor)
      expect(win.navigator.userAgent).to.eq(expected.userAgent)
      expect(win.matchMedia('(hover: none)').matches).to.eq(true)
    })
  })

  it('supports landscape variants using real per-orientation data', () => {
    // iPhone 16 landscape isn't a naive swap of the portrait viewport — the
    // mobile toolbar takes a different amount of space in landscape, so this
    // must match the catalog's real landscape entry, not width/height swapped.
    cy.emulate('iPhone 16 landscape')
    cy.visit('/')

    const expected = devices['iPhone 16 landscape']

    cy.window().should((win) => {
      expect(win.innerWidth).to.eq(expected.viewport.width)
      expect(win.innerHeight).to.eq(expected.viewport.height)
    })
  })

  it('supports landscape variants generated via the naive-swap fallback', () => {
    // Galaxy S25 has no cited landscape source, so its landscape entry is
    // auto-generated by swapping the portrait width/height.
    cy.emulate('Galaxy S25 landscape')
    cy.visit('/')

    cy.window().should((win) => {
      expect(win.innerWidth).to.eq(devices['Galaxy S25'].viewport.height)
      expect(win.innerHeight).to.eq(devices['Galaxy S25'].viewport.width)
    })
  })

  it('matches the iPad Pro 11 descriptor exactly', () => {
    cy.emulate('iPad Pro 11')
    cy.visit('/')

    const expected = devices['iPad Pro 11']

    cy.window().should((win) => {
      expect(win.innerWidth).to.eq(expected.viewport.width)
      expect(win.innerHeight).to.eq(expected.viewport.height)
      expect(win.devicePixelRatio).to.eq(expected.deviceScaleFactor)
      expect(win.navigator.userAgent).to.eq(expected.userAgent)
      expect(win.matchMedia('(pointer: coarse)').matches).to.eq(true)
    })
  })

  it('matches the Galaxy Z Fold 6 descriptor exactly', () => {
    cy.emulate('Galaxy Z Fold 6')
    cy.visit('/')

    const expected = devices['Galaxy Z Fold 6']

    cy.window().should((win) => {
      expect(win.innerWidth).to.eq(expected.viewport.width)
      expect(win.innerHeight).to.eq(expected.viewport.height)
      expect(win.navigator.userAgent).to.eq(expected.userAgent)
    })
  })

  it('accepts a custom descriptor instead of a catalog name', () => {
    cy.emulate({
      viewport: { width: 500, height: 900 },
      deviceScaleFactor: 2,
      isMobile: true,
      hasTouch: true,
      userAgent: 'custom-agent-string',
    })
    cy.visit('/')

    cy.window().should((win) => {
      expect(win.innerWidth).to.eq(500)
      expect(win.navigator.userAgent).to.eq('custom-agent-string')
    })
  })

  it('applies locale, timezone, and geolocation overrides from a custom descriptor', () => {
    // No catalog entry sets these fields, so this is the only runtime coverage
    // for that part of the DeviceDescriptor -> CDP wiring in src/commands.ts.
    cy.emulate({
      viewport: { width: 400, height: 800 },
      deviceScaleFactor: 2,
      isMobile: true,
      hasTouch: true,
      userAgent: 'custom-agent-string',
      locale: 'fr-FR',
      timezoneId: 'Asia/Tokyo',
      geolocation: { latitude: 35.6762, longitude: 139.6503 },
    })
    cy.visit('/')

    cy.window().should((win) => {
      expect(win.navigator.language).to.eq('fr-FR')
      expect(new Intl.DateTimeFormat().resolvedOptions().timeZone).to.eq('Asia/Tokyo')
    })

    cy.window().then((win) => {
      return new Cypress.Promise((resolve) => {
        win.navigator.geolocation.getCurrentPosition((position) => {
          expect(position.coords.latitude).to.eq(35.6762)
          expect(position.coords.longitude).to.eq(139.6503)
          resolve()
        })
      })
    })
  })

  it('clears locale/timezone/geolocation overrides on reset', () => {
    cy.emulate({
      viewport: { width: 400, height: 800 },
      deviceScaleFactor: 2,
      isMobile: true,
      hasTouch: true,
      userAgent: 'custom-agent-string',
      locale: 'fr-FR',
      timezoneId: 'Asia/Tokyo',
      geolocation: { latitude: 35.6762, longitude: 139.6503 },
    })
    cy.resetEmulation()
    cy.visit('/')

    cy.window().should((win) => {
      expect(win.navigator.language).to.not.eq('fr-FR')
      expect(new Intl.DateTimeFormat().resolvedOptions().timeZone).to.not.eq('Asia/Tokyo')
    })
  })

  it('applies colorScheme, reducedMotion, and forcedColors overrides from a custom descriptor', () => {
    // No catalog entry sets these fields, so this is the only runtime coverage
    // for that part of the DeviceDescriptor -> CDP wiring in src/commands.ts.
    cy.emulate({
      viewport: { width: 400, height: 800 },
      deviceScaleFactor: 2,
      isMobile: true,
      hasTouch: true,
      userAgent: 'custom-agent-string',
      colorScheme: 'dark',
      reducedMotion: 'reduce',
      forcedColors: 'active',
    })
    cy.visit('/')

    cy.window().should((win) => {
      expect(win.matchMedia('(prefers-color-scheme: dark)').matches).to.eq(true)
      expect(win.matchMedia('(prefers-reduced-motion: reduce)').matches).to.eq(true)
      expect(win.matchMedia('(forced-colors: active)').matches).to.eq(true)
    })
  })

  it('clears colorScheme/reducedMotion/forcedColors overrides on reset', () => {
    // Unlike locale/timezone (thousands of possible values, so 'fr-FR'/'Asia/Tokyo'
    // can never collide with a real default), these three media features are
    // binary/ternary and reflect a real OS-level setting once un-forced -- CI
    // runners genuinely differ here (e.g. Windows/macOS runners were observed
    // defaulting prefers-reduced-motion/forced-colors differently than Ubuntu's).
    // So this captures each runner's actual baseline first, forces the OPPOSITE
    // of it (guaranteeing a real, observable change), then asserts reset returns
    // to that captured baseline rather than assuming a fixed universal default.
    cy.visit('/')
    cy.window().then((win) => {
      const baseline = {
        dark: win.matchMedia('(prefers-color-scheme: dark)').matches,
        reduce: win.matchMedia('(prefers-reduced-motion: reduce)').matches,
        forced: win.matchMedia('(forced-colors: active)').matches,
      }

      cy.emulate({
        viewport: { width: 400, height: 800 },
        deviceScaleFactor: 2,
        isMobile: true,
        hasTouch: true,
        userAgent: 'custom-agent-string',
        colorScheme: baseline.dark ? 'light' : 'dark',
        reducedMotion: baseline.reduce ? 'no-preference' : 'reduce',
        forcedColors: baseline.forced ? 'none' : 'active',
      })
      cy.resetEmulation()
      cy.visit('/')

      cy.window().should((win2) => {
        expect(win2.matchMedia('(prefers-color-scheme: dark)').matches).to.eq(baseline.dark)
        expect(win2.matchMedia('(prefers-reduced-motion: reduce)').matches).to.eq(baseline.reduce)
        expect(win2.matchMedia('(forced-colors: active)').matches).to.eq(baseline.forced)
      })
    })
  })

  it('throws a clear, actionable error for an unknown device name', (done) => {
    cy.on('fail', (err) => {
      expect(err.message).to.include('unknown device')
      expect(err.message).to.include('Nokia 3310')
      done()
    })
    cy.emulate('Nokia 3310')
  })

  it('throws a clear error on a non-Chromium browser instead of a raw CDP failure', (done) => {
    // CI only runs Chrome, so this stubs Cypress.browser to exercise the actual
    // guard in src/commands.ts without a separate Firefox job. Regression test for
    // a real bug: before this guard existed, cy.emulate() on Firefox surfaced as
    // "An unknown error has occurred: [object Object]" with zero indication of
    // what was wrong (verified manually against a real Firefox run).
    cy.stub(Cypress, 'browser').value({ name: 'firefox', family: 'firefox' })
    cy.on('fail', (err) => {
      expect(err.message).to.include('cy.emulate() requires a Chromium-family browser')
      expect(err.message).to.include('firefox')
      done()
    })
    cy.emulate('iPhone 16')
  })

  it('does not break the afterEach reset hook on a non-Chromium browser', () => {
    // Regression test for a real bug: resetEmulation() used to run Browser.*
    // CDP commands unconditionally, which broke EVERY test's afterEach hook on
    // Electron (and would on Firefox too) — even specs that never call
    // cy.emulate() at all. See src/commands.ts and src/cdp.ts.
    cy.stub(Cypress, 'browser').value({ name: 'firefox', family: 'firefox' })
    cy.resetEmulation() // must no-op cleanly, not throw
  })

  it('does not leak emulation state into a test that never calls cy.emulate (auto-reset)', () => {
    // Relies on the auto-reset afterEach hook having run after the previous test.
    //
    // Deliberately NOT asserting matchMedia('(hover: none)') here. That default
    // for a never-emulated page is a platform/CI-runner detail — e.g. Linux CI
    // running Chrome under a virtual display may not report a pointer device
    // the same way local dev does — not something this library controls or
    // resetEmulation() can be blamed for. UA and innerWidth below are
    // unambiguous regardless of platform: a real environment's UA is never
    // literally 'custom-agent-string', and innerWidth only matches the
    // configured default when no viewport override is active.
    cy.visit('/')
    cy.window().should((win) => {
      expect(win.navigator.userAgent).to.not.include('iPhone')
      expect(win.navigator.userAgent).to.not.eq('custom-agent-string')
      expect(win.innerWidth).to.eq(Cypress.config('viewportWidth'))
    })
  })

  it('logs in on a real site and opens the mobile menu (README usage example)', () => {
    cy.emulate('Galaxy S25')
    cy.visit('/')
    cy.get('[data-test="username"]').type('standard_user')
    cy.get('[data-test="password"]').type('secret_sauce')
    cy.get('[data-test="login-button"]').click()
    cy.get('[data-test="open-menu"]').should('be.visible')
    cy.get('#react-burger-menu-btn').click()
    cy.window().its('navigator.maxTouchPoints').should('be.greaterThan', 0)
  })
})

describe('cy.rotate', () => {
  it('rotates a named catalog device to landscape using the real catalog entry, not a naive swap', () => {
    cy.emulate('iPhone 16')
    cy.visit('http://localhost:4599')

    let orientationChangeFired = false
    cy.window().then((win) => win.addEventListener('orientationchange', () => (orientationChangeFired = true)))

    cy.rotate('landscape')

    const expected = devices['iPhone 16 landscape']
    cy.window().should((win) => {
      // 734x343 (real per-orientation data) — NOT 659x393 (naive swap of portrait)
      expect(win.innerWidth).to.eq(expected.viewport.width)
      expect(win.innerHeight).to.eq(expected.viewport.height)
      expect(win.screen.orientation.type).to.eq('landscape-primary')
      expect(win.screen.orientation.angle).to.eq(90)
      expect(orientationChangeFired).to.eq(true)
    })
  })

  it('rotates back to portrait, idempotently', () => {
    cy.emulate('iPhone 16')
    cy.visit('http://localhost:4599')
    cy.rotate('landscape')
    cy.rotate('portrait')
    cy.rotate('portrait') // calling it twice in a row must not double-flip

    const expected = devices['iPhone 16']
    cy.window().should((win) => {
      expect(win.innerWidth).to.eq(expected.viewport.width)
      expect(win.innerHeight).to.eq(expected.viewport.height)
      expect(win.screen.orientation.type).to.eq('portrait-primary')
    })
  })

  it('rotates a custom descriptor via a width/height swap (no catalog entry to look up)', () => {
    cy.emulate({
      viewport: { width: 400, height: 800 },
      deviceScaleFactor: 2,
      isMobile: true,
      hasTouch: true,
      userAgent: 'custom-agent-string',
    })
    cy.visit('http://localhost:4599')
    cy.rotate('landscape')
    cy.window().should((win) => {
      expect(win.innerWidth).to.eq(800)
      expect(win.innerHeight).to.eq(400)
      expect(win.navigator.userAgent).to.eq('custom-agent-string')
    })
  })

  it('throws a clear, actionable error if called before cy.emulate() in the same test', (done) => {
    cy.on('fail', (err) => {
      expect(err.message).to.include('cy.rotate() requires cy.emulate() to have been called first')
      done()
    })
    cy.rotate('landscape')
  })
})
